version: '3'
services:
  redis:
    image: redis
  backend:
    image: rifqio/multi-backend
    mem_limit: 128
    hostname: backend
    environment:
      - DATABASE_HOST=$DBHOST
      - DATABASE_USER=$DBUSER
      - DATABASE_DB=$DBDB
      - DATABASE_PASSWORD=$DBPASSWORD
      - DATABASE_PORT=$DBPORT
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  frontend:
    image: rifqio/multi-frontend
    hostname: frontend
    mem_limit: 128
    environment:
      - WDS_SOCKET_PORT=0
  nginx:
    image: rifqio/multi-nginx
    hostname: nginx
    mem_limit: 128
    ports:
      - "80:80"
    